# Default values for Network International
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: niapp
replicaCount: 1
image:
  repository: VALUE_TO_BE_OVERRIDDEN
  tag: latest

imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  externalPort: 80
  internalPort: 5000

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  path: /
  hostname: VALUE_TO_BE_OVERRIDDEN

secrets: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

applicationInsights:
  InstrumentationKey: VALUE_TO_BE_OVERRIDDEN
